[application]
name = "Bebeu Editor"

[web.app]
# HTML title tag content
title = "Bebeu Editor"

# include `assets` in web platform
[web.resource]
# Additional CSS style files
style = []
# Additional JavaScript files
script = []

[web.resource.dev]
# JavaScript code file
# serve: [dev-server] only
script = []

[web.watcher]
watch_path = ["src/**/*", "assets"]
